<?php

/**
 * Implements hook_help().
 */
function webprofiler_help($path, $arg) {
  switch ($path) {
    case 'admin/config/development/profiler/list':
      $storage = Drupal::config('webprofiler.config')->get('storage');
      $output = '<p>' . t('Profiles stored with %storage service.', array('%storage' => $storage)) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function webprofiler_theme() {
  return array(
    'webprofiler_loader' => array(
      'template' => 'Profiler/webprofiler_loader',
      'variables' => array('token' => NULL),
    ),
    'webprofiler_toolbar' => array(
      'template' => 'Profiler/webprofiler_toolbar',
      'variables' => array('token' => NULL, 'templates' => array(), 'profile' => NULL, 'profiler_url' => NULL),
    ),
    'webprofiler_panel' => array(
      'template' => 'Profiler/webprofiler_panel',
      'variables' => array(
        'template' => array(),
        'profile' => NULL,
        'name' => NULL,
        'summary' => NULL,
      ),
    ),
    'webprofiler_resume' => array(
      'template' => 'Profiler/webprofiler_resume',
      'variables' => array(
        'template' => array(),
        'profile' => NULL,
        'name' => NULL
      ),
    ),
  );
}

/**
 * Implements hook_permission().
 */
function webprofiler_permission() {
  $perms = array(
    'access web profiler' => array(
      'title' => t('Access web profiler'),
      'description' => t('Access web profiler.'),
    ),
  );

  return $perms;
}

/**
 * Implements hook_file_download().
 */
function webprofiler_file_download($uri) {
  $scheme = file_uri_scheme($uri);
  $target = file_uri_target($uri);
  if ($scheme == 'temporary' && $target == 'profiles.tar.gz') {
    return array(
      'Content-disposition' => 'attachment; filename="profiles.tar.gz"',
    );
  }
}

/**
 * Implements hook_cache_flush().
 */
function webprofiler_cache_flush() {
  $config = \Drupal::configFactory()->get('webprofiler.config');

  if ($config->get('purge_on_cache_clear')) {
    $profiler = \Drupal::service('profiler');
    $profiler->purge();
  }
}

/**
 * Implements hook_page_build().
 */
function webprofiler_page_build(&$page) {
  if (!\Drupal::currentUser()->hasPermission('access developer toolbar')) {
    return;
  }

  $page['#attached']['library'][] = 'webprofiler/webprofiler';
}
